expr {=
from fir.controls.utils import cls, firScopeOptsEnc;
def LazyArea {=
	var
		instanceName: null
		cssBaseClass: 'fir-LazyArea'
		moduleName: 'fir/controls/LazyArea/LazyArea'
		config: {};
	do {*
		<div class="{=cls 'block'}" data-fir-module="{{moduleName}}">
			<input type="hidden" data-fir-opts="{=firScopeOptsEnc fields: ['config'] }"/>
			<div class="{=cls 'container'}"></div>
		</div>
	*}
}
}