expr {=
from fir.controls.utils import cls, firScopeOptsEnc;
def ValidationController {=
	var
		instanceName: null
		moduleName: 'fir/controls/Validation/Controller/Controller'
		cssBaseClass: 'fir-ValidationController';
	do {*
	<div class="{=cls 'block'}" data-fir-module="{{moduleName}}">
		<input type="hidden" data-fir-opts="{=firScopeOptsEnc}"/>
		<div class="{=cls 'popupWrapper'}"></div>
	</div>
	*}
}
}